[build]
  command = "bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  node_bundler = "esbuild"
  node_version = "18" # Or higher, depending on your preference and Next.js version
  directory = ".netlify/functions" # Default output directory for Next.js functions